# -*- coding: utf-8 -*-
"""El texto de las paginas de servicio: gestoria, crecimiento y publico.

Misma regla que en el resto: no se inventa nada. Ningun precio, ningun
plazo, ningun cliente. Cada pagina dice tambien para quien NO es, que es
la parte que se suele callar y la que mas confianza da.
"""

GESTORIA = {
    "contabilidad": {
        "titulo": "Contabilidad",
        "lema": "Contabilidad al día, sin esperas ni sorpresas",
        "entradilla": "Sigues perdiendo horas con facturas y papeles, y cuando preguntas por tus números, esperas al cierre del trimestre para que te manden un PDF.",
        "secciones": [
            ("La manera tradicional no te da información",
             ["Hasta ahora, llevar la contabilidad era así: juntas facturas, las envías a tu gestor y esperas semanas. Al final recibes un PDF que no entiendes y que ya es historia vieja.",
              "El problema no es la contabilidad en sí. Es que siempre llegas tarde: no sabes si tu negocio va bien hasta que alguien te lo cuenta cuando ya no puedes reaccionar."]),
            ("Llevamos tu contabilidad al día, sin que te des cuenta",
             ["Olvídate de guardar papeles en una carpeta. Con nuestro software, registramos tus movimientos y conciliamos tus bancos. Cuando llega el momento del cierre, ya está todo hecho.",
              "No esperamos a que nos mandes nada. Nosotros nos encargamos de actualizar tus libros con cada operación, desde la factura de un proveedor hasta la amortización de una máquina."]),
            ("Tus libros, siempre delante de ti",
             ["La diferencia está en el acceso: tú ves tus asientos, tu plan contable y tus cuentas en tiempo real desde tu panel. No dependes de que te enviemos información por correo.",
              "Eso significa que puedes saber cómo va tu negocio antes de tomar decisiones. No esperas tres meses para descubrir si de verdad ganas dinero."]),
        ],
        "incluye": [
            "Contabilidad al día, sin depender de tus envíos trimestrales",
            "Asientos contables registrados",
            "Plan contable adecuado a tu actividad",
            "Conciliación bancaria de tus cuentas",
            "Cálculo de amortizaciones de tu inmovilizado",
            "Cierre contable y cuentas anuales",
            "Consulta de tus libros online en cualquier momento",
        ],
        "limites": "Este servicio no es para ti si solo buscas presentar impuestos y no quieres saber cómo está tu negocio. Tampoco si necesitas llevar contabilidades muy complejas de grupos empresariales o con operaciones internacionales de gran volumen: para eso necesitas un equipo interno o una consultora especializada. Contaes cubre la contabilidad del día a día, con rigor, para pymes, autónomos y startups que quieren tomar decisiones con datos reales.",
    },
    "fiscal": {
        "titulo": "Fiscal y modelos",
        "lema": "Tus impuestos al día, sin sustos de última hora",
        "entradilla": "¿Te suena eso de que Hacienda te reclama porque un modelo se presentó mal o tarde? Nosotros lo preparamos, lo revisamos y lo firmamos para que tú no tengas que preocuparte.",
        "secciones": [
            ("Tu día a día fiscal, en orden",
             ["Cada trimestre tienes que presentar el IVA, las retenciones y, si eres autónomo, el pago fraccionado. Y a final de año, los resúmenes. Si lo haces tú, te toca controlar fechas, calcular bases y cruzar datos. Si se te pasa algo, llega la carta de Hacienda.",
              "Nosotros nos encargamos de todo ese proceso: preparamos los modelos, los revisamos y los presentamos. Y en realidad ni siquiera tienes que pasarnos nada: las facturas ya están dentro, porque el programa donde las emites es el mismo con el que llevamos tus libros."]),
            ("Una persona colegiada firma, no un robot",
             ["Nuestra inteligencia artificial prepara los borradores de cada modelo a partir de tus libros contables. Pero nadie presenta nada sin que un gestor colegiado lo revise, lo firme y lo envíe a Hacienda. La responsabilidad es humana, con nombre y apellidos, no de un algoritmo.",
              "Y antes de presentar, la IA cruza tus libros y te avisa si algo descuadra. Por ejemplo, si un gasto no tiene factura válida o un tipo de IVA no cuadra con lo declarado. Así puedes corregirlo a tiempo, en lugar de enterarte meses después con una regularización."]),
            ("Qué modelos llevamos por ti",
             ["Para autónomos y pymes, los más habituales: el 303 de IVA, los 111 y 115 de retenciones, el 130 de pago fraccionado y el 390 resumen anual del IVA. También el 347 de operaciones con terceros y el 190 de retenciones de trabajadores y profesionales.",
              "Si tienes una sociedad, además preparamos el 200 de Impuesto sobre Sociedades y el 349 de operaciones intracomunitarias. Siempre con el mismo método: primero la máquina detecta lo raro, después la persona decide y presenta."]),
            ("Avisamos antes, no después",
             ["Ninguna declaración sale sin que alguien la haya comprobado. Si la IA encuentra una discrepancia entre tus libros y lo que corresponde declarar, te lo decimos antes de presentar. Tú nos aclaras la duda o nos envías el documento que falta, y entonces sí, presentamos.",
              "Eso significa que no te enteras de los problemas cuando ya está todo enviado. Trabajamos para que la declaración que sale sea la correcta, aunque a veces implique un pequeño tira y afloja contigo para cuadrar un dato."]),
        ],
        "incluye": [
            "Presentación del 303 de IVA trimestral y del 390 resumen anual",
            "Presentación de los 111 y 115 de retenciones de IRPF",
            "Presentación del 130 de pago fraccionado para autónomos en estimación directa",
            "Presentación del 349 de operaciones intracomunitarias",
            "Presentación del 347 de operaciones con terceros",
            "Presentación del 190 de retenciones e ingresos a cuenta",
            "Presentación del 200 de Impuesto sobre Sociedades",
            "Revisión previa de cada borrador por un gestor colegiado",
            "Aviso automático de descuadres o inconsistencias antes de presentar",
        ],
        "limites": "Lo que sí conviene decir: no hacemos planificación fiscal agresiva ni ingeniería para pagar menos de lo que toca. Tampoco llevamos grupos de sociedades con consolidación fiscal ni entidades no residentes, que piden una especialización distinta. Y si ya hay un procedimiento abierto con Hacienda de una etapa anterior, hay que mirarlo caso por caso antes de comprometernos a nada.",
    },
    "laboral": {
        "titulo": "Laboral y nominas",
        "lema": "Contratar y pagar nóminas sin quebraderos de cabeza",
        "entradilla": "Contratar a alguien es un lío: contratos, nóminas, seguridad social, finiquitos. Y si te equivocas, las sanciones no avisan.",
        "secciones": [
            ("El coste real de contratar",
             ["Antes de hacer una oferta, necesitas saber cuánto te va a costar. No es solo el salario: ahí entran la seguridad social, las retenciones y posibles bonificaciones.",
              "Te calculamos el coste real, te recomendamos el tipo de contrato y te explicamos las consecuencias de cada opción. Así decides con números encima de la mesa, no con suposiciones."]),
            ("Trámites sin sustos",
             ["Cada alta, baja, prórroga o modificación tiene su plazo y su formulario. Un retraso puede suponer una sanción; un error en el tipo de contrato, una mala jugada más adelante.",
              "Nosotros llevamos todos esos trámites con la seguridad de quien lo hace cada día. Tú firmas cuando toca y sigues con tu negocio."]),
            ("Nóminas y cotizaciones al día",
             ["Cada mes preparamos tus nóminas, los seguros sociales y el modelo 111 con las retenciones. Tu equipo cobra puntual y Hacienda y la Seguridad Social, también.",
              "También gestionamos partes de baja, registro de jornada y finiquitos cuando llega el momento. Todo ordenado y comprobado."]),
            ("Asesoramiento cuando cambia algo",
             ["Una vacación, una baja, un ERTE, un despido... estas situaciones llegan sin avisar y conviene actuar bien.",
              "Te explicamos qué hacer, qué opciones tienes y qué consecuencias tiene cada decisión. Sin tecnicismos y con lenguaje claro."]),
        ],
        "incluye": [
            "Análisis y formalización de contratos de trabajo",
            "Altas, bajas y modificaciones en la Seguridad Social",
            "Nóminas mensuales y recibos de salario",
            "Seguros sociales y modelo 111 con retenciones de IRPF",
            "Finiquitos y liquidaciones",
            "Gestión de partes de baja, incapacidad temporal y accidentes",
            "Registro de jornada y asesoramiento sobre el coste real de contratar",
        ],
        "limites": "No es tu servicio si solo tienes colaboradores autónomos o si eres una gran empresa con convenios colectivos muy complejos; en ese caso necesitas una configuración a medida. Tampoco incluye representación en juicios laborales: si llega esa vía, lo deriva a un abogado laboralista.",
    },
    "legal": {
        "titulo": "Legal",
        "lema": "Revisa antes de firmar y evitarás el juicio",
        "entradilla": "Firmas contratos que no entiendes y aceptas cláusulas que no has leído. El problema no es lo que firmas, sino lo que no revisaste a tiempo.",
        "secciones": [
            ("Firmar sin leer tiene precio",
             ["Un autónomo firma un arrendamiento y descubre que responde con su piso. Un socio acepta una cláusula de no competencia que le impide trabajar el día que sale. El contrato es ley entre las partes, y cuando llega el conflicto, te das cuenta de lo que firmaste.",
              "La mayoría de los problemas legales no vienen de lo que está en el contrato, sino de lo que no está: el plazo, la penalización, el alcance. Nosotros te lo decimos antes de que pongas tu firma."]),
            ("La revisión preventiva, tu escudo",
             ["Revisamos cada contrato antes de que lo firmes. Te explicamos en lenguaje claro qué significa cada cláusula y qué riesgo asumes. Si algo no te conviene, te decimos dónde negociar.",
              "El coste de una revisión es una parte mínima de lo que pagarías en un pleito. Pero el beneficio principal no es el ahorro: es saber que no te van a sorprender."]),
            ("Más que revisar: te lo construimos",
             ["No solo miramos el contrato que te traen. También redactamos los tuyos: condiciones de venta, acuerdos con proveedores, cláusulas de confidencialidad. Te damos la documentación que protege tu negocio desde el día uno.",
              "Y si estás montando la empresa, nos encargamos de la constitución, los estatutos y los pactos de socios. Para que los problemas con los socios no empiecen el primer año, sino que se eviten desde el inicio."]),
            ("Legal integrado con tu gestión",
             ["En Contaes el asesor legal no trabaja en una burbuja. Colabora con tu contabilidad y tu fiscalidad: cada decisión legal la ves también en números. Te avisamos si una cláusula tiene impacto fiscal o laboral.",
              "No necesitas buscar un despacho aparte. Tienes un equipo que conoce tu empresa entera, no solo un contrato. Y si surge un litigio, te coordinamos con especialistas."]),
        ],
        "incluye": [
            "Constitución de sociedades y redacción de estatutos",
            "Pactos de socios y acuerdos de accionistas",
            "Contratos mercantiles: compraventa, servicio, distribución, colaboración",
            "Condiciones de venta para tu web o tienda",
            "Revisión de contratos antes de firmar",
            "Protección de datos y cumplimiento RGPD",
            "Propiedad intelectual: marcas, nombres, diseños",
        ],
        "limites": "Este servicio es preventivo. No llevamos juicios ni contenciosos; si el conflicto ya está en el juzgado, te remitimos a un despacho especializado. Tampoco es para grandes corporaciones ni para fusiones internacionales. Nuestro foco es el autónomo, la startup y la pyme que necesita protegerse en el día a día sin sustos.",
    },
}

CRECIMIENTO = {
    "cfo": {
        "titulo": "CFO a tu lado",
        "lema": "Un director financiero sin contratarlo, para decidir con datos",
        "entradilla": "Hay un momento en que los números de tu negocio ya no caben en tu cabeza. Sabes que facturas, pero no si cada cliente, producto o línea te deja margen real. Ahí es donde un CFO marca la diferencia: convierte la incertidumbre en un plan claro.",
        "secciones": [
            ("La contabilidad dice lo que pasó. El CFO, lo que va a pasar",
             ["Tu gestoría te presenta las cuentas de hace tres meses. Bien. Pero eso no te dice si vas a poder pagar las nóminas el mes que viene, ni si un cliente que crece mucho te está haciendo perder dinero en realidad.",
              "El CFO a tu lado mira hacia delante. Con los datos de tu negocio, construye una previsión de tesorería, detecta problemas de margen antes de que duelan y te dice qué conviene dejar de hacer, impulsar o renegociar."]),
            ("Qué hace exactamente tu CFO a tu lado",
             ["Cada trimestre tienes una foto clara: qué líneas de negocio tiran, cuáles comen recursos sin devolver nada, qué clientes son rentables de verdad y cuáles solo parecen grandes. Nada de intuiciones. Son tus números, explicados con criterio.",
              "Además, preparamos el presupuesto anual y lo revisamos contigo de forma periódica. Cuando hablas con un banco, un socio o un inversor, tienes los papeles que sustentan tu historia. Cuando hay que decidir entre una oportunidad nueva y el foco, tienes un análisis con el que apoyarte."]),
            ("Cómo trabajamos en Contaes",
             ["No montamos un sistema complejo lleno de informes incomprensibles. Partimos de tu contabilidad real, la que ya llevamos en Contaes, y la convertimos en una herramienta de decisión. Cuadro de mando sencillo, reuniones periódicas y un interlocutor que conoce tu negocio.",
              "El software de gestión con IA nos ayuda a detectar patrones y anticipar desviaciones. Pero el criterio es humano. El tuyo, para decidir. El nuestro, para acompañarte con números, análisis y planificación."]),
            ("Esto no va de dejar de ser gestoría",
             ["Si solo necesitas presentar impuestos y llevar la contabilidad, tu gestoría ya lo hace. Este servicio es para cuando quieres ir un paso más allá: dejar de reaccionar y empezar a decidir.",
              "No es un servicio para todos los días. Es una revisión estratégica periódica y un acompañamiento continuo. Tú sigues llevando el día a día de tu empresa. Nosotros nos encargamos de que ningún número se te escape."]),
        ],
        "incluye": [
            "Presupuesto anual ajustado a tu realidad y objetivos",
            "Previsión de tesorería renovada para anticipar falta de liquidez",
            "Control de márgenes por línea de negocio para saber qué te da dinero",
            "Análisis de rentabilidad por cliente y producto, no por intuición",
            "Cuadro de mando con los indicadores que de verdad importan",
            "Reuniones periódicas de revisión y seguimiento",
            "Interpretación y recomendaciones concretas para cada decisión",
        ],
        "limites": "Esto no es la contabilidad: la contabilidad la llevamos aparte, y de hecho es la que alimenta estos números. Tampoco sustituye a una dirección financiera a jornada completa en una empresa grande. Y no es para quien acaba de empezar: sin unos meses de datos detrás no hay nada que analizar, solo opiniones.",
    },
    "cmo": {
        "titulo": "CMO a tu lado",
        "lema": "Marketing con cabeza, sin depender de un director.",
        "entradilla": "¿Cuánto de tu presupuesto de publicidad se va por el desagüe? Sin alguien que mida cada campaña, nunca sabrás qué anuncio trajo a ese cliente que firmó.",
        "secciones": [
            ("El problema: gastar sin saber",
             ["Cada semana sale una campaña nueva. Facebook, Google, Instagram, el banner de turno. Y al final del mes miras el extracto y piensas: ¿esto ha traído algo?",
              "Las agencias te enseñan clics, impresiones y alcance. Pero eso no paga tus facturas. Lo que necesitas saber es qué palabra de búsqueda, qué anuncio o qué contenido acabó en una llamada, un correo o una firma."]),
            ("Lo que hace un CMO a tu lado",
             ["Un director de marketing no va de creativo. Va de decidir dónde poner el dinero y de medir qué devuelve. Eso es lo que hacemos: definimos tu posicionamiento y tu propuesta de valor para que no digas 'somos los mejores' sin prueba.",
              "Después montamos un plan de captación: qué canales funcionan, qué mensaje llega a tu cliente real y qué contenido te hace aparecer cuando te buscan.",
              "Y no se queda en la teoría. Revisamos cada semana la cifra que importa: cuánto cuesta adquirir un cliente que paga y de dónde viene."]),
            ("La medición que de verdad cuenta",
             ["Olvídate de métricas bonitas. Con nosotros tendrás un cuadro de mando sencillo con las fuentes de tus clientes reales.",
              "Sabrás si esa inversión en Google Ads te trae consultas que cierran, si el artículo que publicaste en tu web es el que más ventas genera, o si el newsletter que envías cada mes sigue mereciendo la pena.",
              "Cuando algo no funciona, se corta. Cuando algo funciona, se alimenta. Así de simple y así de difícil de hacer si no tienes a alguien dedicado."]),
            ("Cómo trabajamos, sin rollos",
             ["Primero, una sesión de diagnóstico contigo y con tu equipo comercial. Después, definimos el plan y lo ponemos en marcha.",
              "No somos un agencia que se sienta a esperar el brief. Nos reunimos contigo de forma periódica, con datos actualizados y decisiones concretas.",
              "Y no queremos matrimonios eternos: si después de unos meses ves que no es para ti, se acaba. Sin permanencia ni excusas."]),
        ],
        "incluye": [
            "Diagnóstico de tu posicionamiento actual y el de tus competidores",
            "Definición de propuesta de valor clara y verificable",
            "Plan de captación con canales prioritarios y presupuesto recomendado",
            "Calendario editorial y contenidos para atraer clientes que te buscan",
            "Revisión y ajuste de tu presencia en buscadores (SEO local y de nicho)",
            "Sistema de medición por campaña, palabra clave o contenido, hasta el cierre de venta",
            "Reunión periódica con informe de qué trae clientes y qué sobra",
        ],
        "limites": "Este servicio no es para multinacionales que necesitan un equipo de 20 personas, ni sustituye a un departamento comercial. Si tu problema es de producto o de precios, eso hay que arreglarlo antes de invertir en captación. Tampoco gestionamos la ejecución diaria de redes sociales ni la creación de anuncios: eso lo hace tu equipo o los proveedores que te recomendamos.",
    },
    "prospeccion": {
        "titulo": "Prospeccion comercial",
        "lema": "Clientes potenciales encontrados con método, no con suerte.",
        "entradilla": "Dejas de esperar a que el teléfono suene y empiezas a llamar a quien de verdad te necesita. Transformamos una lista de nombres en conversaciones comerciales con criterio, sin spam.",
        "secciones": [
            ("El punto de partida",
             ["Tienes un buen producto y una web aceptable, pero los meses pasan y el cliente no llama. Si vendes solo al que llega, dependes de la casualidad.",
              "La prospección comercial ordenada cambia las reglas: decides tú a quién quieres vender, preparas el mensaje y haces seguimiento hasta que toca cerrar o descartar. No es magia, es un proceso repetible."]),
            ("Cómo lo hacemos",
             ["Primero definimos un perfil de cliente que tenga problema, presupuesto y urgencia. Si no encaja ahí, no está en la lista. Después construimos una base acotada y la enriquecemos con datos públicos.",
              "Lanzamos secuencias de contacto por correo y llamadas: pocas, pero bien hechas. Medimos cada apertura, respuesta y reunión para ajustar el mensaje. El seguimiento deja de depender de la memoria de nadie.",
              "La IA hace el trabajo repetitivo: buscar, ordenar, unificar datos y preparar el borrador del mensaje. Las personas conversan. Nadie recibe un correo robo que hable solo de ti."]),
            ("Dónde entra la IA",
             ["La parte aburrida es investigar treinta empresas y anotar quién decide, en qué sector está y qué podría interesarle. Eso lo hace una máquina y lo deja listo para revisar.",
              "El mensaje lo prepara la IA, pero no se envía directamente: una persona lo adapta y decide. La conversación, la llamada y la negociación son humanas. Así parece que no te has escondido detrás de un robot."]),
            ("Qué cambia en tu negocio",
             ["Tienes una cartera de oportunidades viva. Sabes cuántas conversaciones has abierto, cuántas siguen vivas y cuándo hay que insistir.",
              "También aprendes qué mensajes funcionan y cuáles no. La siguiente ronda sale mejor que la anterior. El objetivo no es molestar a mil desconocidos: es encontrar a los veinte que te necesitan y empezar la conversación."]),
        ],
        "incluye": [
            "Definición del perfil de cliente ideal",
            "Construcción de listas segmentadas y verificadas",
            "Secuencias de correo con seguimiento programado",
            "Guion de llamadas de cualificación",
            "Registro de todas las interacciones en tu CRM o en una hoja compartida",
            "Informe de resultados con aperturas, respuestas y reuniones",
            "IA para investigar, ordenar y preparar mensajes que luego revisa una persona",
        ],
        "limites": "Este servicio no es para quien quiere escribir a media base de datos sin criterio. Prospección masiva sin segmentación quema la imagen de la marca y, con el tiempo, tu base de datos. Tampoco hacemos telemarketing de cierre: nos centramos en generar y cualificar oportunidades, no en negociar el contrato final. Si tu mercado es tan pequeño que ya conoces a todos los posibles clientes, quizá no lo necesitas.",
    },
    "bots": {
        "titulo": "Bot de llamadas y WhatsApp",
        "lema": "Respuestas al momento, y una persona cuando hace falta",
        "entradilla": "Pierdes ventas por no responder a tiempo en teléfono y WhatsApp. Este bot contesta solo las preguntas recurrentes y te pasa el relevo cuando toca.",
        "secciones": [
            ("No estás, pero el teléfono sigue sonando",
             ["Cada llamada perdida puede ser un presupuesto que se va a otro. Aunque trabajes solo o en equipo pequeño, no puedes estar pendiente todo el día.",
              "La mayoría de preguntas se repiten: si tienes hueco, cuánto cuesta, dónde está un pedido. Son importantes para quien pregunta, pero te roban tiempo."]),
            ("Un bot que hace el trabajo primero",
             ["El servicio recoge la llamada y atiende a esa persona con un guion hecho con tu información real: horarios, tarifas, estados de pedido, reservas de cita.",
              "En WhatsApp responde al momento, estés donde estés. Si la conversación se sale de lo previsto o el cliente pide a una persona, te avisa y te conecta en segundos."]),
            ("La regla de oro: honestidad y relevo sin fricciones",
             ["El bot se presenta como bot. Nada de hacerse pasar por humano ni de obligar a repetir tres veces lo mismo.",
              "Quien quiera hablar contigo, dice 'persona' y el sistema escala. No hay muros ni menús interminables. Así el bot resuelve lo que puede y tú te quedas solo con lo que requiere ojo humano."]),
            ("Lo que puedes delegar sin miedo",
             ["Reservar una cita en tu agenda, confirmar un horario, contar el estado de un envío o dar un precio de salida: tareas repetitivas que ahora hacen otra vez, pero sin ti.",
              "También recoge el motivo de la llamada y te deja un resumen para que llegues a la conversación sabiendo quién es y qué necesita."]),
        ],
        "incluye": [
            "Contestador automático que atiende llamadas cuando no estás disponible.",
            "Respuestas inmediatas en WhatsApp a preguntas frecuentes (horarios, precios, pedidos, citas).",
            "El bot se identifica como bot y avisa cuando va a transferir a una persona.",
            "Escalado a humanos con contexto: el cliente no tiene que repetir el motivo.",
            "Integración con tu calendario para ofrecer y confirmar citas según disponibilidad real.",
            "Resumen de cada conversación en un panel, con notificación cuando hay que intervenir.",
            "Edición de guiones y respuestas desde un portal sencillo, sin tocar código.",
        ],
        "limites": "No sirve para negociar grandes acuerdos ni para dar soporte técnico avanzado. Tampoco sustituye al personal en relaciones complejas o cuando el cliente necesita una conversación de confianza. El bot trabaja bien con preguntas concretas y repetitivas; si tu negocio se basa en una venta consultiva muy larga o en atención emocional, necesitarás personas casi siempre.",
    },
    "financiacion": {
        "titulo": "Financiacion publica y privada",
        "lema": "Subvenciones e inversión privada, sin perder el tiempo",
        "entradilla": "Buscar financiación por tu cuenta acaba en una pila de requisitos y fechas imposibles. La mayoría de solicitudes se rechazan por defectos de forma o por pedir la ayuda equivocada.",
        "secciones": [
            ("El problema: los fallos que no ves",
             ["Cada convocatoria tiene sus plazos, su documentación y sus letras pequeñas. Un solo error de formulario te deja fuera, aunque tu proyecto sea bueno.",
              "Lo difícil no es encontrar ayudas, sino presentar exactamente lo que piden, con el encaje correcto. Y eso es justo donde más solicitudes mueren."]),
            ("Dos vías complementarias",
             ["Dinero público: subvenciones, avales, préstamos participativos y programas de innovación. No se devuelve, pero exige cumplir requisitos formales y presentar en plazo.",
              "Dinero privado: préstamos bancarios, leasing, business angels y capital riesgo. Se devuelve con retorno, y para conseguirlo necesitas un caso de inversión creíble.",
              "Nosotros trabajamos ambas vías sin casarte con ninguna. Preparamos la documentación, buscamos la convocatoria o el inversor que encaja y te acompañamos en el proceso."]),
            ("Cómo lo hacemos",
             ["Primero entendemos tu situación real: qué necesitas, qué puedes ofrecer y qué circunstancias importan. Sin eso, no tiene sentido buscar nada.",
              "Después buscamos opciones que encajan de verdad, no las que más suenan. Cuidamos la forma, los plazos y la coherencia de la solicitud o del dossier.",
              "Te acompañamos hasta el final: revisión previa, presentación, y seguimiento. No desaparecemos cuando se envía el formulario."]),
            ("Para quién es",
             ["Para autónomos, startups y pymes que necesitan dinero pero no pueden permitirse perder semanas en burocracia.",
              "No hace falta que domines la jerga de subvenciones ni de finanzas. Sí hace falta que traigas la documentación básica de tu empresa y ganas de responder con claridad."]),
        ],
        "incluye": [
            "Búsqueda de convocatorias y programas de ayudas que encajen con tu actividad",
            "Elaboración de la solicitud completa con los requisitos formales",
            "Preparación de la documentación para ayudas públicas",
            "Análisis y preparación del caso para préstamo bancario o leasing",
            "Elaboración de un dossier o pitch para inversores privados",
            "Acompañamiento en el proceso de negociación con entidades o inversores",
            "Revisión previa para evitar errores de forma que te descarten",
        ],
        "limites": "Este servicio no consigue financiación imposible. Si tu empresa no tiene viabilidad o no cumple los requisitos, no haremos milagros. No trabajamos con ideas sin desarrollo ni con empresas que no puedan demostrar sus números. En lo público, la decisión final la toma la administración; en lo privado, el banco o el inversor. Y tú también pones de tu parte: necesitamos acceso real a la información de tu negocio y que respondas en los plazos que marca cada convocatoria o negociación.",
    },
    "internacionalizacion": {
        "titulo": "Internacionalizacion",
        "lema": "Vende en el extranjero sin sustos fiscales",
        "entradilla": "Has cerrado tu primer pedido desde otro país y ahora no sabes si toca IVA español o el de allí. Vender fuera sin aclarar antes cada operación es la forma más cara de aprender.",
        "secciones": [
            ("El error de vender fuera sin saber dónde tributa",
             ["El entusiasmo por lograr un cliente en Alemania o Francia hace que muchas veces se envíe la mercancía antes de preguntarse si esa venta es una operación intracomunitaria, una exportación o simplemente una venta a distancia. Y esa pregunta no es burocrática: decide quién cobra el IVA, a qué tipo y quién responde ante Hacienda.",
              "Si te equivocas, el margen de la operación se puede ir en recargos, intereses o, peor, en un problema con la Agencia Tributaria que acaba comiéndote semanas de trabajo. No es cuestión de miedo, es cuestión de orden."]),
            ("Primero, ponemos la fiscalidad en su sitio",
             ["Cada venta fuera de España tiene su propia casuística: no es lo mismo vender a un particular en Alemania que a un empresario en Polonia, ni mandar a Reino Unido que a México. Nosotros analizamos tus operaciones reales y te decimos, antes de que factures, qué IVA aplica, dónde lo declaras y qué registro necesitas.",
              "Además, revisamos si tus proveedores o clientes te piden el NIF-IVA, si tienes que darte de alta en algún registro de otro país o si la operación requiere justificantes de transporte para poder aplicar la exención. El objetivo es que ninguna factura salga sin tener claro el tratamiento fiscal."]),
            ("Contratos, aduanas y adaptar lo que vendes",
             ["No basta con el IVA. Si vas a trabajar con distribuidores o importadores, necesitas contratos que fijen las reglas: quién paga el transporte, qué pasa con las devoluciones, qué ley rige el contrato. Y si envías fuera de la UE, la aduana exige que el producto, el embalaje y la documentación cuadren al milímetro.",
              "También ayuda a que tu propuesta encaje en cada mercado: precios con y sin impuestos, condiciones de pago, idioma, certificaciones exigidas. Nosotros nos encargamos de coordinar toda esa parte contigo y con tu socio local, para que tú te centres en vender."]),
            ("Filnet, el compañero de viaje para abrir mercado",
             ["La parte fiscal y administrativa la llevamos nosotros, pero abrir mercado requiere alguien que conozca el terreno. Por eso trabajamos con Filnet, una empresa hermana especializada en ayudarte a entrar en nuevos países. Ellos se ocupan del análisis de mercado, la búsqueda de canales y la adaptación de tu oferta al cliente local.",
              "Contigo no vas a hablar con un call center remoto. Tienes un equipo en España que habla tu idioma y que coordina con Filnet para que los temas fiscales y los comerciales vayan al mismo ritmo. Todo contado en reuniones directas, sin humo."]),
        ],
        "incluye": [
            "Análisis y clasificación de tus ventas: intracomunitarias, exportaciones o ventas a distancia",
            "Asesoramiento sobre el IVA de cada operación y el registro de alta necesario en cada país",
            "Preparación y revisión de la documentación para aduanas en exportaciones fuera de la UE",
            "Redacción o revisión de contratos con distribuidores y agentes comerciales",
            "Adaptación de tu propuesta comercial a cada mercado: precios, condiciones, idioma y requisitos",
            "Coordinación con Filnet para el análisis de mercado y el plan de entrada",
            "Seguimiento fiscal de tus operaciones internacionales en tu contabilidad y tus impuestos",
        ],
        "limites": "No cubrimos la logística física: transporte, almacén en destino ni distribución. Y aunque la parte legal la llevamos nosotros, montar una filial o un establecimiento permanente en otro país exige apoyo local en ese país; lo decimos antes, no después. Si tu plan es vender online a consumidores en varios países de la UE, hay reglas de IVA propias que hay que mirar una por una.",
    },
}

PARA = {
    "autonomos": {
        "titulo": "Autonomos",
        "lema": "Tu gestoría para autónomos, sin sustos ni letra pequeña",
        "entradilla": "Muchos autónomos viven con la duda de si lo están haciendo bien. Si no sabes qué gastos deduces o cuánto te queda, no es culpa tuya: nadie te lo explicó.",
        "secciones": [
            ("Lo que realmente necesita un autónomo",
             ["Te damos de alta y nos encargamos de trámites y cuota. Te avisamos de cambios y de lo que te conviene.",
              "Presentamos tus impuestos trimestrales y anuales: IVA, modelo 130 o módulos. Y calculamos tu renta de cada mes para que sepas lo que de verdad ganas."]),
            ("Sin miedo a dejar algo sin declarar",
             ["La mayoría de inspecciones nacen de errores por desconocimiento, no de mala fe. Ese gasto que creías deducible no lo es, o al revés. Nosotros revisamos tus facturas y te decimos qué se puede y qué no.",
              "Te damos a ti las pautas, al día, para que sepas lo que entra y lo que no. Y si Hacienda llama, te acompañamos."]),
            ("¿Cuándo compensa pasar a sociedad?",
             ["No hay una regla mágica. Depende de lo que factures, de tus gastos y de lo que quieras hacer con el dinero. Te damos una opinión honesta cuando llega el momento.",
              "Solemos recomendarlo cuando tu base imponible sube de forma estable, o si quieres deducir costes que como autónomo no puedes. Pero no empujamos a nadie a una sociedad si no aporta."]),
            ("Cómo te quitamos trabajo",
             ["Subes tus facturas o las hacemos nosotros. Te avisamos de cada plazo y lo dejamos todo presentado. Tú te dedicas a trabajar.",
              "Y cuando algo no cuadre, te llamamos antes de que sea tarde."]),
        ],
        "incluye": [
            "Alta de autónomo y tramitación de la cuota.",
            "Declaración trimestral de IVA.",
            "Impuesto sobre la renta: modelo 130 o la opción por módulos.",
            "Revisión de gastos deducibles y no deducibles, con criterio claro.",
            "Emisión y control de facturas sencillo.",
            "Informe mensual de lo que te queda de verdad.",
            "Consejo sobre el momento de pasarte a sociedad.",
        ],
        "limites": "Si tu situación es muy sencilla (pocas facturas, ningún empleado, ningún gasto que dudar) probablemente puedas apañarte solo, y te lo diremos. Esto tiene sentido cuando ya hay volumen suficiente para que un error cueste más que la cuota, o cuando el tiempo que dedicas a papeles es tiempo que no dedicas a facturar.",
    },
    "startups": {
        "titulo": "Startups",
        "lema": "La contabilidad que no lastra tu ronda de inversión.",
        "entradilla": "Tu startup no puede llevar la contabilidad como un trámite. El día que un inversor pida números, necesitas unos libros que aguanten una due diligence.",
        "secciones": [
            ("El problema",
             ["Llevar la contabilidad como un trámite es el error más caro para una startup.",
              "Cuando un inversor pide ver los números, los libros aparecen desordenados, sin clasificar y con gastos de I+D sin rastrear. Ese día no se puede improvisar."]),
            ("Qué hacemos",
             ["Acompañamos a la startup desde la constitución: creamos la sociedad, definimos el pacto de socios con tu abogado y montamos una contabilidad pensada para aguantar una due diligence.",
              "Llevamos el día a día con control de caja y runway, y clasificamos cada gasto para que las deducciones de I+D y las ayudas públicas de innovación no se queden en el camino."]),
            ("Listos para la ronda",
             ["Preparamos la información financiera en el formato que espera un inversor: cuentas claras, métricas de gestión y una trazabilidad real de tus gastos.",
              "No esperamos a que llegue la ronda: trabajamos cada mes para que la due diligence sea un proceso rápido y sin sustos."]),
        ],
        "incluye": [
            "Constitución de la sociedad y definición del pacto de socios con tu asesoría legal",
            "Contabilidad y fiscalidad preparadas para una due diligence",
            "Control de caja y cálculo del runway mes a mes",
            "Registro de gastos de I+D y preparación de deducciones",
            "Documentación financiera lista para inversores",
            "Detección y gestión de ayudas públicas de innovación",
        ],
        "limites": "Dos avisos honestos. Ordenamos la casa para que una ronda sea posible, pero no buscamos inversores por ti ni negociamos las condiciones: eso lo hacéis vosotros, y hay quien se dedica solo a eso. Y si la empresa aún no tiene actividad, casi todo esto puede esperar; te lo diremos en la primera llamada en vez de venderte un paquete que no vas a usar.",
    },
    "pymes": {
        "titulo": "Pymes",
        "lema": "Creciste. Ahora tu administración crece contigo.",
        "entradilla": "Tener 50 empleados y administrar como cuando tenías 5 es un cuello de botella. Te montamos un sistema único, con gestores expertos, para que crezcas sin sustos ni freno.",
        "secciones": [
            ("Cuando crecer desordena la gestión",
             ["Empiezas con cinco y todo cabe en una hoja de cálculo. Pero llegas a cuarenta, abres una segunda línea de negocio o empiezas a exportar, y esa forma de trabajar se cae.",
              "El resultado es trabajar de más, pagar sanciones por retrasos que no viste venir y tomar decisiones de caja mirando solo lo que pasó ayer."]),
            ("Un solo sistema, con personas al otro lado",
             ["Sustituimos la maraña de programas sueltos y hojas de cálculo por una plataforma única de gestión. Contabilidad, facturas, nóminas y tesorería conviven en el mismo sitio, con una sola base de datos.",
              "Nuestro equipo de gestores se encarga del día a día: revisa, presenta y te avisa con tiempo. Tú no necesitas saber contabilidad. Solo saber hacia dónde llevas la empresa."]),
            ("Control de márgenes y tesorería previsible",
             ["¿Sabes qué producto o servicio te da más margen? ¿Cuánto necesitas en caja para pagar las nóminas del próximo trimestre? Sin un sistema único, esas respuestas son corazonadas.",
              "Con el cuadro de mando de Contaes ves la rentabilidad de cada línea de negocio, la previsión de tesorería y los impuestos que vienen. Se acabaron las sorpresas."]),
            ("Ayuda para crecer sin descontrolarte",
             ["Contratar, abrir una sede nueva o lanzar un producto requiere un soporte administrativo y financiero a la altura. Acompañamos ese crecimiento para que la estructura no te frene.",
              "Y cuando necesites financiación o dar el salto fuera, lo montamos con nuestros Servicios de Crecimiento, con el mismo enfoque práctico."]),
        ],
        "incluye": [
            "Contabilidad y fiscalidad presentadas por un gestor experto.",
            "Nóminas y gestión laboral para equipos de 5 a 50 personas.",
            "Plataforma propia: facturas, gastos y clientes centralizados.",
            "Sustitución de la hoja de cálculo por informes de márgenes.",
            "Previsión de tesorería e impuestos, sin sustos a fin de mes.",
            "Cuadro de mando para ver la rentabilidad real del negocio.",
            "Un equipo asesor que responde, no un portal sin voz.",
        ],
        "limites": "Este servicio tiene sentido cuando consolidas un equipo de cinco o más personas. Si eres autónomo sin asalariados o tu facturación es muy sencilla, te servirá más nuestra asesoría de base. Y si solo buscas que te presenten los impuestos sin que nadie te opine sobre el negocio, no somos tu gestoría. Pero si quieres que la administración quede resuelta mientras tú diriges, esto es lo tuyo.",
    },
}
